### ISSUE TITLE
Improve UI feedback

### ISSUE THREAD

**Issue by kevinboss** [Mibokess/cil-2021#1]
Currently the user is unable to see if the application is running properly or not.

Application seems to be stuck here:
<img width="983" alt="image" src="https://user-images.githubusercontent.com/4927587/134247852-bd11790c-6759-4b64-bf28-19efc35e01c9.png">

**Comment by Mibokess** [comment]
It is probably not stuck just extremely slow as you don't have a GPU available.
The progress is indicated in your output (no progress as of now).

For more UI you may use the .ipynb versions.
